### ISSUE TITLE
"just dl-rhcos" failing due to missing image

### ISSUE THREAD

**Issue by aravindhp** [rabugopsl/fedora-installer-libvirt-smoke#11]
Executing `just dl-rhcos` results in:
```
(master ✓) fedora-installer-libvirt-smoke just dl-rhcos
~/devel/github/fedora-installer-libvirt-smoke/ignore ~/devel/github/fedora-installer-libvirt-smoke
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168  100   168    0     0   1953      0 --:--:-- --:--:-- --:--:--  1953

gzip: stdin: not in gzip format
```
This is because http://aos-ostree.rhev-ci-vms.eng.rdu2.redhat.com/rhcos/images/cloud/latest/rhcos-qemu.qcow2.gz no longer exist. It has moved to http://aos-ostree.rhev-ci-vms.eng.rdu2.redhat.com/rhcos/old-v1-pipeline-content-do-not-use/images/cloud/latest/rhcos-qemu.qcow2.gz but given the directory name it is unclear if it is safe to use.

**Comment by rabugopsl** [comment]
Sorry for the delay. The `just dl-rhcos` command has been updated to the most recent image.
